---
title: "FinalProject2"
output: pdf_document
---

```{r}
library(atus)
library(dplyr)
```

```{r}
#ungroup(atusact)
#atuscps
#atusresp
```

```{r}
# Find average family income by educational attainment
avg_income_by_edu <- atuscps 
avg_income_by_edu <- avg_income_by_edu %>%
  separate(famincome, into=c('income_low','income_high'), sep='-',convert=TRUE)%>%
  mutate(income_low = as.integer(income_low)) %>%
  drop_na() %>%
  mutate(fam_income_mid = (income_high+income_low)/2) %>%
  group_by(education=edu) %>%
  summarise(N = n(),
            avg_income = mean(fam_income_mid)) %>%
  arrange(avg_income)
avg_income_by_edu
```
```{r}
#Visualize results
ggplot(data=avg_income_by_edu, aes(x=education, y=avg_income)) +
  geom_bar(stat='identity') +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
# Investigate by region
# Find average family income by educational attainment
avg_income_by_edu_region <- atuscps 
avg_income_by_edu_region <-avg_income_by_edu_region %>%
  separate(famincome, into=c('income_low','income_high'), sep='-',convert=TRUE)%>%
  mutate(income_low = as.integer(income_low)) %>%
  drop_na() %>%
  mutate(fam_income_mid = (income_high+income_low)/2) %>%
  group_by(region,edu) %>%
  summarise(N = n(),
            avg_income = mean(fam_income_mid)) %>%
  arrange(avg_income)
avg_income_by_edu_region
```

```{r}
# Compare regions by income
region_df <- avg_income_by_edu_region %>%
  group_by(region) %>%
  summarise(N=n(),
            avg_income = mean(avg_income)) %>%
  arrange(avg_income)
ggplot(region_df, aes(x=region, y=avg_income, label=avg_income)) +
  geom_bar(stat='identity') +
  geom_text(aes(label = signif(avg_income, digits = 3)))
```

```{r}
# Compare income by region and edu
ggplot(avg_income_by_edu_region, aes(x=region, y=avg_income)) +
    geom_bar(position='stack',stat='identity') +
    scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    geom_text(aes(label = signif(avg_income, digits = 3)), angle = 90, 
              nudge_y = -10000, color = 'white') +
    facet_grid(~ edu)
```


